// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sql.proto
// Protobuf Java Version: 4.31.1

package com.changgeng.proto;

@com.google.protobuf.Generated
public final class SqlInfo {
  private SqlInfo() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      SqlInfo.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SqlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sql)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string op = 1;</code>
     * @return The op.
     */
    java.lang.String getOp();
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string op = 1;</code>
     * @return The bytes for op.
     */
    com.google.protobuf.ByteString
        getOpBytes();

    /**
     * <pre>
     * 表名
     * </pre>
     *
     * <code>string table = 2;</code>
     * @return The table.
     */
    java.lang.String getTable();
    /**
     * <pre>
     * 表名
     * </pre>
     *
     * <code>string table = 2;</code>
     * @return The bytes for table.
     */
    com.google.protobuf.ByteString
        getTableBytes();

    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string before = 3;</code>
     * @return The before.
     */
    java.lang.String getBefore();
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string before = 3;</code>
     * @return The bytes for before.
     */
    com.google.protobuf.ByteString
        getBeforeBytes();

    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string after = 4;</code>
     * @return The after.
     */
    java.lang.String getAfter();
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string after = 4;</code>
     * @return The bytes for after.
     */
    com.google.protobuf.ByteString
        getAfterBytes();

    /**
     * <pre>
     * 返回解析是否成功
     * </pre>
     *
     * <code>bool isSuccess = 5;</code>
     * @return The isSuccess.
     */
    boolean getIsSuccess();
  }
  /**
   * <pre>
   * 消息类型定义
   * </pre>
   *
   * Protobuf type {@code Sql}
   */
  public static final class Sql extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Sql)
      SqlOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Sql.class.getName());
    }
    // Use Sql.newBuilder() to construct.
    private Sql(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Sql() {
      op_ = "";
      table_ = "";
      before_ = "";
      after_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.changgeng.proto.SqlInfo.internal_static_Sql_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.changgeng.proto.SqlInfo.internal_static_Sql_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.changgeng.proto.SqlInfo.Sql.class, com.changgeng.proto.SqlInfo.Sql.Builder.class);
    }

    public static final int OP_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object op_ = "";
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string op = 1;</code>
     * @return The op.
     */
    @java.lang.Override
    public java.lang.String getOp() {
      java.lang.Object ref = op_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        op_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string op = 1;</code>
     * @return The bytes for op.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOpBytes() {
      java.lang.Object ref = op_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        op_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object table_ = "";
    /**
     * <pre>
     * 表名
     * </pre>
     *
     * <code>string table = 2;</code>
     * @return The table.
     */
    @java.lang.Override
    public java.lang.String getTable() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        table_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 表名
     * </pre>
     *
     * <code>string table = 2;</code>
     * @return The bytes for table.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTableBytes() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        table_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BEFORE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object before_ = "";
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string before = 3;</code>
     * @return The before.
     */
    @java.lang.Override
    public java.lang.String getBefore() {
      java.lang.Object ref = before_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        before_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string before = 3;</code>
     * @return The bytes for before.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBeforeBytes() {
      java.lang.Object ref = before_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        before_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AFTER_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object after_ = "";
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string after = 4;</code>
     * @return The after.
     */
    @java.lang.Override
    public java.lang.String getAfter() {
      java.lang.Object ref = after_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        after_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string after = 4;</code>
     * @return The bytes for after.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAfterBytes() {
      java.lang.Object ref = after_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        after_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSUCCESS_FIELD_NUMBER = 5;
    private boolean isSuccess_ = false;
    /**
     * <pre>
     * 返回解析是否成功
     * </pre>
     *
     * <code>bool isSuccess = 5;</code>
     * @return The isSuccess.
     */
    @java.lang.Override
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(op_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, op_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(table_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, table_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(before_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, before_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(after_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, after_);
      }
      if (isSuccess_ != false) {
        output.writeBool(5, isSuccess_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(op_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, op_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(table_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, table_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(before_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, before_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(after_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, after_);
      }
      if (isSuccess_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isSuccess_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.changgeng.proto.SqlInfo.Sql)) {
        return super.equals(obj);
      }
      com.changgeng.proto.SqlInfo.Sql other = (com.changgeng.proto.SqlInfo.Sql) obj;

      if (!getOp()
          .equals(other.getOp())) return false;
      if (!getTable()
          .equals(other.getTable())) return false;
      if (!getBefore()
          .equals(other.getBefore())) return false;
      if (!getAfter()
          .equals(other.getAfter())) return false;
      if (getIsSuccess()
          != other.getIsSuccess()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OP_FIELD_NUMBER;
      hash = (53 * hash) + getOp().hashCode();
      hash = (37 * hash) + TABLE_FIELD_NUMBER;
      hash = (53 * hash) + getTable().hashCode();
      hash = (37 * hash) + BEFORE_FIELD_NUMBER;
      hash = (53 * hash) + getBefore().hashCode();
      hash = (37 * hash) + AFTER_FIELD_NUMBER;
      hash = (53 * hash) + getAfter().hashCode();
      hash = (37 * hash) + ISSUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSuccess());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.changgeng.proto.SqlInfo.Sql parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.changgeng.proto.SqlInfo.Sql parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.changgeng.proto.SqlInfo.Sql parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.changgeng.proto.SqlInfo.Sql parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.changgeng.proto.SqlInfo.Sql prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息类型定义
     * </pre>
     *
     * Protobuf type {@code Sql}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sql)
        com.changgeng.proto.SqlInfo.SqlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.changgeng.proto.SqlInfo.internal_static_Sql_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.changgeng.proto.SqlInfo.internal_static_Sql_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.changgeng.proto.SqlInfo.Sql.class, com.changgeng.proto.SqlInfo.Sql.Builder.class);
      }

      // Construct using com.changgeng.proto.SqlInfo.Sql.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        op_ = "";
        table_ = "";
        before_ = "";
        after_ = "";
        isSuccess_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.changgeng.proto.SqlInfo.internal_static_Sql_descriptor;
      }

      @java.lang.Override
      public com.changgeng.proto.SqlInfo.Sql getDefaultInstanceForType() {
        return com.changgeng.proto.SqlInfo.Sql.getDefaultInstance();
      }

      @java.lang.Override
      public com.changgeng.proto.SqlInfo.Sql build() {
        com.changgeng.proto.SqlInfo.Sql result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.changgeng.proto.SqlInfo.Sql buildPartial() {
        com.changgeng.proto.SqlInfo.Sql result = new com.changgeng.proto.SqlInfo.Sql(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.changgeng.proto.SqlInfo.Sql result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.op_ = op_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.table_ = table_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.before_ = before_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.after_ = after_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.isSuccess_ = isSuccess_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.changgeng.proto.SqlInfo.Sql) {
          return mergeFrom((com.changgeng.proto.SqlInfo.Sql)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.changgeng.proto.SqlInfo.Sql other) {
        if (other == com.changgeng.proto.SqlInfo.Sql.getDefaultInstance()) return this;
        if (!other.getOp().isEmpty()) {
          op_ = other.op_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTable().isEmpty()) {
          table_ = other.table_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getBefore().isEmpty()) {
          before_ = other.before_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getAfter().isEmpty()) {
          after_ = other.after_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getIsSuccess() != false) {
          setIsSuccess(other.getIsSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                op_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                table_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                before_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                after_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                isSuccess_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object op_ = "";
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string op = 1;</code>
       * @return The op.
       */
      public java.lang.String getOp() {
        java.lang.Object ref = op_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          op_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string op = 1;</code>
       * @return The bytes for op.
       */
      public com.google.protobuf.ByteString
          getOpBytes() {
        java.lang.Object ref = op_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          op_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string op = 1;</code>
       * @param value The op to set.
       * @return This builder for chaining.
       */
      public Builder setOp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        op_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string op = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOp() {
        op_ = getDefaultInstance().getOp();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string op = 1;</code>
       * @param value The bytes for op to set.
       * @return This builder for chaining.
       */
      public Builder setOpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        op_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object table_ = "";
      /**
       * <pre>
       * 表名
       * </pre>
       *
       * <code>string table = 2;</code>
       * @return The table.
       */
      public java.lang.String getTable() {
        java.lang.Object ref = table_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          table_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 表名
       * </pre>
       *
       * <code>string table = 2;</code>
       * @return The bytes for table.
       */
      public com.google.protobuf.ByteString
          getTableBytes() {
        java.lang.Object ref = table_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          table_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 表名
       * </pre>
       *
       * <code>string table = 2;</code>
       * @param value The table to set.
       * @return This builder for chaining.
       */
      public Builder setTable(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        table_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 表名
       * </pre>
       *
       * <code>string table = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTable() {
        table_ = getDefaultInstance().getTable();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 表名
       * </pre>
       *
       * <code>string table = 2;</code>
       * @param value The bytes for table to set.
       * @return This builder for chaining.
       */
      public Builder setTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        table_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object before_ = "";
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string before = 3;</code>
       * @return The before.
       */
      public java.lang.String getBefore() {
        java.lang.Object ref = before_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          before_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string before = 3;</code>
       * @return The bytes for before.
       */
      public com.google.protobuf.ByteString
          getBeforeBytes() {
        java.lang.Object ref = before_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          before_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string before = 3;</code>
       * @param value The before to set.
       * @return This builder for chaining.
       */
      public Builder setBefore(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        before_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string before = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBefore() {
        before_ = getDefaultInstance().getBefore();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string before = 3;</code>
       * @param value The bytes for before to set.
       * @return This builder for chaining.
       */
      public Builder setBeforeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        before_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object after_ = "";
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string after = 4;</code>
       * @return The after.
       */
      public java.lang.String getAfter() {
        java.lang.Object ref = after_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          after_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string after = 4;</code>
       * @return The bytes for after.
       */
      public com.google.protobuf.ByteString
          getAfterBytes() {
        java.lang.Object ref = after_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          after_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string after = 4;</code>
       * @param value The after to set.
       * @return This builder for chaining.
       */
      public Builder setAfter(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        after_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string after = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAfter() {
        after_ = getDefaultInstance().getAfter();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string after = 4;</code>
       * @param value The bytes for after to set.
       * @return This builder for chaining.
       */
      public Builder setAfterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        after_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private boolean isSuccess_ ;
      /**
       * <pre>
       * 返回解析是否成功
       * </pre>
       *
       * <code>bool isSuccess = 5;</code>
       * @return The isSuccess.
       */
      @java.lang.Override
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <pre>
       * 返回解析是否成功
       * </pre>
       *
       * <code>bool isSuccess = 5;</code>
       * @param value The isSuccess to set.
       * @return This builder for chaining.
       */
      public Builder setIsSuccess(boolean value) {

        isSuccess_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回解析是否成功
       * </pre>
       *
       * <code>bool isSuccess = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Sql)
    }

    // @@protoc_insertion_point(class_scope:Sql)
    private static final com.changgeng.proto.SqlInfo.Sql DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.changgeng.proto.SqlInfo.Sql();
    }

    public static com.changgeng.proto.SqlInfo.Sql getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sql>
        PARSER = new com.google.protobuf.AbstractParser<Sql>() {
      @java.lang.Override
      public Sql parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Sql> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sql> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.changgeng.proto.SqlInfo.Sql getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sql_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sql_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tsql.proto\"R\n\003Sql\022\n\n\002op\030\001 \001(\t\022\r\n\005table\030" +
      "\002 \001(\t\022\016\n\006before\030\003 \001(\t\022\r\n\005after\030\004 \001(\t\022\021\n\t" +
      "isSuccess\030\005 \001(\010B\036\n\023com.changgeng.protoB\007" +
      "SqlInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Sql_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sql_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Sql_descriptor,
        new java.lang.String[] { "Op", "Table", "Before", "After", "IsSuccess", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
