
server.port=9091
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driverClassName=org.neo4j.jdbc.bolt.BoltDriver
spring.datasource.url=jdbc:neo4j:bolt://192.168.0.58:7687
spring.datasource.username=neo4j
spring.datasource.password=password
spring.datasource.initiaSize=1
spring.datasource.minIdle=5
spring.datasource.maxActive=5
spring.datasource.maxWait=30

netty.server.port=8888
