// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: neo4j.proto
// Protobuf Java Version: 4.31.1

package com.changgeng.proto;

@com.google.protobuf.Generated
public final class SqlInfoNeo4j {
  private SqlInfoNeo4j() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      SqlInfoNeo4j.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SqlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sql)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * sql语句
     * </pre>
     *
     * <code>string sqlStr = 1;</code>
     * @return The sqlStr.
     */
    java.lang.String getSqlStr();
    /**
     * <pre>
     * sql语句
     * </pre>
     *
     * <code>string sqlStr = 1;</code>
     * @return The bytes for sqlStr.
     */
    com.google.protobuf.ByteString
        getSqlStrBytes();

    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation = 2;</code>
     * @return The operation.
     */
    java.lang.String getOperation();
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation = 2;</code>
     * @return The bytes for operation.
     */
    com.google.protobuf.ByteString
        getOperationBytes();

    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string eventType = 3;</code>
     * @return The eventType.
     */
    java.lang.String getEventType();
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string eventType = 3;</code>
     * @return The bytes for eventType.
     */
    com.google.protobuf.ByteString
        getEventTypeBytes();

    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string elementId = 4;</code>
     * @return The elementId.
     */
    java.lang.String getElementId();
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string elementId = 4;</code>
     * @return The bytes for elementId.
     */
    com.google.protobuf.ByteString
        getElementIdBytes();

    /**
     * <pre>
     * 返回解析是否成功
     * </pre>
     *
     * <code>bool isSuccess = 5;</code>
     * @return The isSuccess.
     */
    boolean getIsSuccess();
  }
  /**
   * <pre>
   * 消息类型定义
   * </pre>
   *
   * Protobuf type {@code Sql}
   */
  public static final class Sql extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Sql)
      SqlOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Sql.class.getName());
    }
    // Use Sql.newBuilder() to construct.
    private Sql(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Sql() {
      sqlStr_ = "";
      operation_ = "";
      eventType_ = "";
      elementId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.changgeng.proto.SqlInfoNeo4j.internal_static_Sql_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.changgeng.proto.SqlInfoNeo4j.internal_static_Sql_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.changgeng.proto.SqlInfoNeo4j.Sql.class, com.changgeng.proto.SqlInfoNeo4j.Sql.Builder.class);
    }

    public static final int SQLSTR_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sqlStr_ = "";
    /**
     * <pre>
     * sql语句
     * </pre>
     *
     * <code>string sqlStr = 1;</code>
     * @return The sqlStr.
     */
    @java.lang.Override
    public java.lang.String getSqlStr() {
      java.lang.Object ref = sqlStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sqlStr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * sql语句
     * </pre>
     *
     * <code>string sqlStr = 1;</code>
     * @return The bytes for sqlStr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSqlStrBytes() {
      java.lang.Object ref = sqlStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object operation_ = "";
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation = 2;</code>
     * @return The operation.
     */
    @java.lang.Override
    public java.lang.String getOperation() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operation_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation = 2;</code>
     * @return The bytes for operation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOperationBytes() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object eventType_ = "";
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string eventType = 3;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string eventType = 3;</code>
     * @return The bytes for eventType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ELEMENTID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object elementId_ = "";
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string elementId = 4;</code>
     * @return The elementId.
     */
    @java.lang.Override
    public java.lang.String getElementId() {
      java.lang.Object ref = elementId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        elementId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string elementId = 4;</code>
     * @return The bytes for elementId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getElementIdBytes() {
      java.lang.Object ref = elementId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        elementId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSUCCESS_FIELD_NUMBER = 5;
    private boolean isSuccess_ = false;
    /**
     * <pre>
     * 返回解析是否成功
     * </pre>
     *
     * <code>bool isSuccess = 5;</code>
     * @return The isSuccess.
     */
    @java.lang.Override
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sqlStr_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, sqlStr_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operation_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, operation_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, eventType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(elementId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, elementId_);
      }
      if (isSuccess_ != false) {
        output.writeBool(5, isSuccess_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sqlStr_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sqlStr_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operation_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, operation_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, eventType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(elementId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, elementId_);
      }
      if (isSuccess_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isSuccess_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.changgeng.proto.SqlInfoNeo4j.Sql)) {
        return super.equals(obj);
      }
      com.changgeng.proto.SqlInfoNeo4j.Sql other = (com.changgeng.proto.SqlInfoNeo4j.Sql) obj;

      if (!getSqlStr()
          .equals(other.getSqlStr())) return false;
      if (!getOperation()
          .equals(other.getOperation())) return false;
      if (!getEventType()
          .equals(other.getEventType())) return false;
      if (!getElementId()
          .equals(other.getElementId())) return false;
      if (getIsSuccess()
          != other.getIsSuccess()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SQLSTR_FIELD_NUMBER;
      hash = (53 * hash) + getSqlStr().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getOperation().hashCode();
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEventType().hashCode();
      hash = (37 * hash) + ELEMENTID_FIELD_NUMBER;
      hash = (53 * hash) + getElementId().hashCode();
      hash = (37 * hash) + ISSUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSuccess());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.changgeng.proto.SqlInfoNeo4j.Sql parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.changgeng.proto.SqlInfoNeo4j.Sql prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息类型定义
     * </pre>
     *
     * Protobuf type {@code Sql}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sql)
        com.changgeng.proto.SqlInfoNeo4j.SqlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.changgeng.proto.SqlInfoNeo4j.internal_static_Sql_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.changgeng.proto.SqlInfoNeo4j.internal_static_Sql_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.changgeng.proto.SqlInfoNeo4j.Sql.class, com.changgeng.proto.SqlInfoNeo4j.Sql.Builder.class);
      }

      // Construct using com.changgeng.proto.SqlInfoNeo4j.Sql.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sqlStr_ = "";
        operation_ = "";
        eventType_ = "";
        elementId_ = "";
        isSuccess_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.changgeng.proto.SqlInfoNeo4j.internal_static_Sql_descriptor;
      }

      @java.lang.Override
      public com.changgeng.proto.SqlInfoNeo4j.Sql getDefaultInstanceForType() {
        return com.changgeng.proto.SqlInfoNeo4j.Sql.getDefaultInstance();
      }

      @java.lang.Override
      public com.changgeng.proto.SqlInfoNeo4j.Sql build() {
        com.changgeng.proto.SqlInfoNeo4j.Sql result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.changgeng.proto.SqlInfoNeo4j.Sql buildPartial() {
        com.changgeng.proto.SqlInfoNeo4j.Sql result = new com.changgeng.proto.SqlInfoNeo4j.Sql(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.changgeng.proto.SqlInfoNeo4j.Sql result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sqlStr_ = sqlStr_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.operation_ = operation_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.eventType_ = eventType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.elementId_ = elementId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.isSuccess_ = isSuccess_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.changgeng.proto.SqlInfoNeo4j.Sql) {
          return mergeFrom((com.changgeng.proto.SqlInfoNeo4j.Sql)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.changgeng.proto.SqlInfoNeo4j.Sql other) {
        if (other == com.changgeng.proto.SqlInfoNeo4j.Sql.getDefaultInstance()) return this;
        if (!other.getSqlStr().isEmpty()) {
          sqlStr_ = other.sqlStr_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getOperation().isEmpty()) {
          operation_ = other.operation_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getEventType().isEmpty()) {
          eventType_ = other.eventType_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getElementId().isEmpty()) {
          elementId_ = other.elementId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getIsSuccess() != false) {
          setIsSuccess(other.getIsSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sqlStr_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                operation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                eventType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                elementId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                isSuccess_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object sqlStr_ = "";
      /**
       * <pre>
       * sql语句
       * </pre>
       *
       * <code>string sqlStr = 1;</code>
       * @return The sqlStr.
       */
      public java.lang.String getSqlStr() {
        java.lang.Object ref = sqlStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sqlStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * sql语句
       * </pre>
       *
       * <code>string sqlStr = 1;</code>
       * @return The bytes for sqlStr.
       */
      public com.google.protobuf.ByteString
          getSqlStrBytes() {
        java.lang.Object ref = sqlStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sqlStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * sql语句
       * </pre>
       *
       * <code>string sqlStr = 1;</code>
       * @param value The sqlStr to set.
       * @return This builder for chaining.
       */
      public Builder setSqlStr(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sqlStr_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sql语句
       * </pre>
       *
       * <code>string sqlStr = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSqlStr() {
        sqlStr_ = getDefaultInstance().getSqlStr();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sql语句
       * </pre>
       *
       * <code>string sqlStr = 1;</code>
       * @param value The bytes for sqlStr to set.
       * @return This builder for chaining.
       */
      public Builder setSqlStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sqlStr_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object operation_ = "";
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string operation = 2;</code>
       * @return The operation.
       */
      public java.lang.String getOperation() {
        java.lang.Object ref = operation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string operation = 2;</code>
       * @return The bytes for operation.
       */
      public com.google.protobuf.ByteString
          getOperationBytes() {
        java.lang.Object ref = operation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string operation = 2;</code>
       * @param value The operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        operation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string operation = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperation() {
        operation_ = getDefaultInstance().getOperation();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>string operation = 2;</code>
       * @param value The bytes for operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        operation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object eventType_ = "";
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string eventType = 3;</code>
       * @return The eventType.
       */
      public java.lang.String getEventType() {
        java.lang.Object ref = eventType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string eventType = 3;</code>
       * @return The bytes for eventType.
       */
      public com.google.protobuf.ByteString
          getEventTypeBytes() {
        java.lang.Object ref = eventType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string eventType = 3;</code>
       * @param value The eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        eventType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string eventType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventType() {
        eventType_ = getDefaultInstance().getEventType();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string eventType = 3;</code>
       * @param value The bytes for eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        eventType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object elementId_ = "";
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string elementId = 4;</code>
       * @return The elementId.
       */
      public java.lang.String getElementId() {
        java.lang.Object ref = elementId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          elementId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string elementId = 4;</code>
       * @return The bytes for elementId.
       */
      public com.google.protobuf.ByteString
          getElementIdBytes() {
        java.lang.Object ref = elementId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          elementId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string elementId = 4;</code>
       * @param value The elementId to set.
       * @return This builder for chaining.
       */
      public Builder setElementId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        elementId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string elementId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearElementId() {
        elementId_ = getDefaultInstance().getElementId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string elementId = 4;</code>
       * @param value The bytes for elementId to set.
       * @return This builder for chaining.
       */
      public Builder setElementIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        elementId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private boolean isSuccess_ ;
      /**
       * <pre>
       * 返回解析是否成功
       * </pre>
       *
       * <code>bool isSuccess = 5;</code>
       * @return The isSuccess.
       */
      @java.lang.Override
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <pre>
       * 返回解析是否成功
       * </pre>
       *
       * <code>bool isSuccess = 5;</code>
       * @param value The isSuccess to set.
       * @return This builder for chaining.
       */
      public Builder setIsSuccess(boolean value) {

        isSuccess_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回解析是否成功
       * </pre>
       *
       * <code>bool isSuccess = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Sql)
    }

    // @@protoc_insertion_point(class_scope:Sql)
    private static final com.changgeng.proto.SqlInfoNeo4j.Sql DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.changgeng.proto.SqlInfoNeo4j.Sql();
    }

    public static com.changgeng.proto.SqlInfoNeo4j.Sql getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sql>
        PARSER = new com.google.protobuf.AbstractParser<Sql>() {
      @java.lang.Override
      public Sql parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Sql> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sql> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.changgeng.proto.SqlInfoNeo4j.Sql getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sql_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sql_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013neo4j.proto\"a\n\003Sql\022\016\n\006sqlStr\030\001 \001(\t\022\021\n\t" +
      "operation\030\002 \001(\t\022\021\n\teventType\030\003 \001(\t\022\021\n\tel" +
      "ementId\030\004 \001(\t\022\021\n\tisSuccess\030\005 \001(\010B#\n\023com." +
      "changgeng.protoB\014SqlInfoNeo4jb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Sql_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sql_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Sql_descriptor,
        new java.lang.String[] { "SqlStr", "Operation", "EventType", "ElementId", "IsSuccess", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
