spring.datasource.druid.driver-class-name=org.postgresql.Driver
spring.datasource.druid.url=jdbc:postgresql://localhost:5432/my_database?currentSchema=public
spring.datasource.druid.username=postgres
spring.datasource.druid.password=postgres
# spring.jpa.database=my_database
spring.datasource.druid.initial-size=1
spring.datasource.druid.min-idle=5
spring.datasource.druid.max-active=5
spring.datasource.druid.max-wait=30

udp.port=8888
# ????????????????????true
udp.ask=false

db.schema=public
